FROM nginx:alpine

# Copy static files to the Nginx HTML directory
COPY frontend/index.html /usr/share/nginx/html/
COPY frontend/style.css /usr/share/nginx/html/

# Expose port 80 for the Nginx container
EXPOSE 80
